/****************************************************************************/
/*! \file HimalayaHardwareSystemStateId.h
 *
 *  \brief All State Ids used by Himalaya hardware system.
 *
 *  $Version:   $ 0.1
 *  $Date:      $ 2013_2_28
 *  $Author:    $ Abe Yang
 *
 *  \b Company:
 *
 *       Leica Microsystems Ltd. Shanghai.
 *
 *  (C) Copyright 2013 by Leica Microsystems Shanghai. All rights reserved.
 *  This is unpublished proprietary source code of Leica. The copyright notice
 *  does not evidence any actual or intended publication.
 *
 */
/****************************************************************************/

#ifndef HIMALAYAHARDWARESYSTEMSTATEID_H
#define HIMALAYAHARDWARESYSTEMSTATEID_H

const quint32 STATE_START_UP	= 520000001;       ///<  Definition/Declaration of variable STATE_START_UP
const quint32 STATE_SELF_TEST	= 520000002;       ///<  Definition/Declaration of variable STATE_SELF_TEST
const quint32 STATE_PRE_HEATING	= 520000003;       ///<  Definition/Declaration of variable STATE_PRE_HEATING
const quint32 STATE_STANDBY	= 520000004;       ///<  Definition/Declaration of variable STATE_STANDBY
const quint32 STATE_RELEASING_PRESSURE	= 520000006;       ///<  Definition/Declaration of variable STATE_RELEASING_PRESSURE
	
const quint32 STATE_PRE_TEST	= 520000200;       ///<  Definition/Declaration of variable STATE_PRE_TEST
const quint32 STATE_PROTOCOL_FIXATION_SUCKING	= 520000201;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_SUCKING
const quint32 STATE_PROTOCOL_FIXATION_DRAINING	= 520000202;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_DRAINING
const quint32 STATE_PROTOCOL_FIXATION_AGATATION_DRAINING	= 520000203;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_AGATATION_DRAINING
const quint32 STATE_PROTOCOL_FIXATION_AGATATION_VORPORA	= 520000204;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_AGATATION_VORPORA
const quint32 STATE_PROTOCOL_FIXATION_AGATATION_RV_TOSEAL	= 520000205;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_AGATATION_RV_TOSEAL
const quint32 STATE_PROTOCOL_FIXATION_AGATATION_RV_TOTUBE	= 520000206;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_AGATATION_RV_TOTUBE
const quint32 STATE_PROTOCOL_FIXATION_STANDBY	= 520000207;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_STANDBY
const quint32 STATE_PROTOCOL_FIXATION_LEVELSENSOR_SUCKING_HEATING	= 520000208;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_LEVELSENSOR_SUCKING_HEATING
const quint32 STATE_PROTOCOL_FIXATION_LEVELSENSOR_AGATITION_HEATING	= 520000209;       ///<  Definition/Declaration of variable STATE_PROTOCOL_FIXATION_LEVELSENSOR_AGATITION_HEATING
	
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_SUCKING	= 520000221;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_SUCKING
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_DRAINING	= 520000222;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_DRAINING
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_AGATATION_DRAINING	= 520000223;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_AGATATION_DRAINING
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_VOR_PORA	= 520000224;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_VOR_PORA
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_RV_TOSEAL	= 520000225;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_RV_TOSEAL
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_RV_TOTUBE	= 520000226;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_RV_TOTUBE
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_LEVELSENSOR_SUCKING_HEATING	= 520000227;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_LEVELSENSOR_SUCKING_HEATING
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_LEVELSENSOR_AGATITION_HEATING	= 520000228;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_DILUTED_LEVELSENSOR_AGATITION_HEATING
	
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_SUCKING	= 520000241;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_SUCKING
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_DRAINING	= 520000242;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_DRAINING
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_AGATATION_DRAINING	= 520000243;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_AGATATION_DRAINING
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_VORPORA	= 520000244;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_VORPORA
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_RV_TOSEAL	= 520000245;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_RV_TOSEAL
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_RV_TOTUBE	= 520000246;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_RV_TOTUBE
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_LEVELSENSOR_SUCKING_HEATING	= 520000247;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_LEVELSENSOR_SUCKING_HEATING
const quint32 STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_LEVELSENSOR_AGATITION_HEATING	= 520000248;       ///<  Definition/Declaration of variable STATE_PROTOCOL_DEHYDRATION_ALCOHOL_UNDILUTED_LEVELSENSOR_AGATITION_HEATING
	
const quint32 STATE_PROTOCOL_INTERMEDIUIM_XYLENE_SUCKING	= 520000261;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INTERMEDIUIM_XYLENE_SUCKING
const quint32 STATE_PROTOCOL_INTERMEDIUIM_XYLENE_DRAINING	= 520000262;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INTERMEDIUIM_XYLENE_DRAINING
const quint32 STATE_PROTOCOL_INTERMEDIUIM_XYLENE_AGATATION_DRAINING	= 520000263;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INTERMEDIUIM_XYLENE_AGATATION_DRAINING
const quint32 STATE_PROTOCOL_INTERMEDIUIM_XYLENE_VORPORA	= 520000264;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INTERMEDIUIM_XYLENE_VORPORA
const quint32 STATE_PROTOCOL_INTERMEDIUIM_XYLENE_RV_TOSEAL	= 520000265;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INTERMEDIUIM_XYLENE_RV_TOSEAL
const quint32 STATE_PROTOCOL_INTERMEDIUIM_XYLENE_RV_TOTUBE	= 520000266;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INTERMEDIUIM_XYLENE_RV_TOTUBE
const quint32 STATE_PROTOCOL_INTERMEDIUIM_XYLENE_LEVELSENSOR_SUCKING_HEATING	= 520000267;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INTERMEDIUIM_XYLENE_LEVELSENSOR_SUCKING_HEATING
const quint32 STATE_PROTOCOL_INTERMEDIUIM_XYLENE_LEVELSENSOR_AGATITION_HEATING	= 520000268;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INTERMEDIUIM_XYLENE_LEVELSENSOR_AGATITION_HEATING
	
const quint32 STATE_PROTOCOL_GETREADYFOR_PARAFFIN	= 520000281;       ///<  Definition/Declaration of variable STATE_PROTOCOL_GETREADYFOR_PARAFFIN
	
const quint32 STATE_PROTOCOL_INFILTRATION_PARAFFIN_SUCKING	= 520000291;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INFILTRATION_PARAFFIN_SUCKING
const quint32 STATE_PROTOCOL_INFILTRATION_PARAFFIN_DRAINING	= 520000292;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INFILTRATION_PARAFFIN_DRAINING
const quint32 STATE_PROTOCOL_INFILTRATION_PARAFFIN_VOR_PORA	= 520000293;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INFILTRATION_PARAFFIN_VOR_PORA
const quint32 STATE_PROTOCOL_INFILTRATION_PARAFFIN_RV_TO_SEAL	= 520000294;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INFILTRATION_PARAFFIN_RV_TO_SEAL
const quint32 STATE_PROTOCOL_INFILTRATION_PARAFFIN_RV_TO_TUBE	= 520000295;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INFILTRATION_PARAFFIN_RV_TO_TUBE
const quint32 STATE_PROTOCOL_INFILTRATION_PARAFFIN_STANDBY	= 520000296;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INFILTRATION_PARAFFIN_STANDBY
const quint32 STATE_PROTOCOL_INFILTRATION_PARAFFIN_LEVELSENSOR_SUCKING_HEATING	= 520000297;       ///<  Definition/Declaration of variable STATE_PROTOCOL_INFILTRATION_PARAFFIN_LEVELSENSOR_SUCKING_HEATING
	
const quint32 STATE_PROTOCOL_CLEANING_XYLENE_SUCKING	= 520000311;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_XYLENE_SUCKING
const quint32 STATE_PROTOCOL_CLEANING_XYLENE_DRAINING	= 520000312;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_XYLENE_DRAINING
const quint32 STATE_PROTOCOL_CLEANING_XYLENE_RV_TOSEAL	= 520000313;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_XYLENE_RV_TOSEAL
const quint32 STATE_PROTOCOL_CLEANING_XYLENE_RV_TOTUBE	= 520000314;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_XYLENE_RV_TOTUBE
const quint32 STATE_PROTOCOL_CLEANING_XYLENE_LEVELSENSOR_SUCKING_HEATING	= 520000315;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_XYLENE_LEVELSENSOR_SUCKING_HEATING
	
const quint32 STATE_PROTOCOL_CLEANING_ALCOHOL_SUCKING	= 520000331;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_ALCOHOL_SUCKING
const quint32 STATE_PROTOCOL_CLEANING_ALCOHOL_DRAINING	= 520000332;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_ALCOHOL_DRAINING
const quint32 STATE_PROTOCOL_CLEANING_ALCOHOL_RV_TOSEAL	= 520000333;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_ALCOHOL_RV_TOSEAL
const quint32 STATE_PROTOCOL_CLEANING_ALCOHOL_RV_TOTUBE	= 520000334;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_ALCOHOL_RV_TOTUBE
const quint32 STATE_PROTOCOL_CLEANING_ALCOHOL_LEVELSENSOR_SUCKING_HEATING	= 520000335;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_ALCOHOL_LEVELSENSOR_SUCKING_HEATING
	
const quint32 STATE_PROTOCOL_CLEANING_WATER_SUCKING	= 520000351;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_WATER_SUCKING
const quint32 STATE_PROTOCOL_CLEANING_WATER_DRAINING	= 520000352;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_WATER_DRAINING
const quint32 STATE_PROTOCOL_CLEANING_WATER_RV_TOSEAL	= 520000353;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_WATER_RV_TOSEAL
const quint32 STATE_PROTOCOL_CLEANING_WATER_RV_TOTUBE	= 520000354;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_WATER_RV_TOTUBE
const quint32 STATE_PROTOCOL_CLEANING_WATER_LEVELSENSOR_SUCKING_HEATING	= 520000355;       ///<  Definition/Declaration of variable STATE_PROTOCOL_CLEANING_WATER_LEVELSENSOR_SUCKING_HEATING

#endif // HIMALAYAHARDWARESYSTEMSTATEID_H
