Himalaya Service Master: SystemTracking::CDlgModifySubModule Class Reference
SystemTracking::CDlgModifySubModule Class Reference
This class provides facility to add/modify submodule configuration.
#include <DlgModifySubModule.h>
Public Slots
void UpdateGUI (void)
Slot for updating the GUI.
void UpdateGUI (const QString &SerialNumber, const QDate &DateOfProduction)
Slot for updating the GUI.
void OnEditSerialNumber (void)
Slot for Edit serial number.
void OnAutoDetect (void)
Slot for auto detect.
void OnSave (void)
Slot for save button.
Signals
void UpdateSubModule (ServiceDataManager::CSubModule &SubModule)
This signal is emitted when a program is updated.
void AutoDetect (ServiceDataManager::CSubModule &SubModule)
This signal is emitted when clicked Auto detect button .
Public Member Functions
CDlgModifySubModule (ServiceDataManager::CSubModule &SubModule, bool HasBoard=false, QWidget *p_Parent=0)
Default constructor.
~CDlgModifySubModule ()
Destructor.
Detailed Description
This class provides facility to add/modify submodule configuration.
Definition at line 43 of file DlgModifySubModule.h.
Constructor & Destructor Documentation
SystemTracking::CDlgModifySubModule::CDlgModifySubModule (ServiceDataManager::CSubModule & SubModule, bool HasBoard = false, QWidget * p_Parent = 0) [explicit]
Default constructor.
Parameters:
[in] SubModule = Reference of SubModule object
[in] HasBoard = flag of Board
[in] p_Parent = parent of widget
Definition at line 29 of file DlgModifySubModule.cpp.
References OnAutoDetect(), OnEditSerialNumber(), OnSave(), and UpdateGUI().
SystemTracking::CDlgModifySubModule::~CDlgModifySubModule ()
Destructor.
Definition at line 105 of file DlgModifySubModule.cpp.
Member Function Documentation
void SystemTracking::CDlgModifySubModule::AutoDetect (ServiceDataManager::CSubModule & SubModule) [signal]
This signal is emitted when clicked Auto detect button .
Parameters:
[in] SubModule = Modified SubModule.
Referenced by OnAutoDetect().
void SystemTracking::CDlgModifySubModule::OnAutoDetect (void) [slot]
Slot for auto detect.
Slot for removing the module.
Definition at line 256 of file DlgModifySubModule.cpp.
References AutoDetect().
Referenced by CDlgModifySubModule().
void SystemTracking::CDlgModifySubModule::OnEditSerialNumber (void) [slot]
Slot for Edit serial number.
Definition at line 120 of file DlgModifySubModule.cpp.
Referenced by CDlgModifySubModule().
void SystemTracking::CDlgModifySubModule::OnSave (void) [slot]
Slot for save button.
This slot is called when Save button is clicked.
Returns:
Returns zero if module does not exists.
Definition at line 188 of file DlgModifySubModule.cpp.
References UpdateSubModule().
Referenced by CDlgModifySubModule().
void SystemTracking::CDlgModifySubModule::UpdateGUI (void) [slot]
Slot for updating the GUI.
Definition at line 131 of file DlgModifySubModule.cpp.
Referenced by CDlgModifySubModule().
void SystemTracking::CDlgModifySubModule::UpdateGUI (const QString & SerialNumber, const QDate & DateOfProduction) [slot]
Slot for updating the GUI.
Parameters:
[in] SerialNumber = Module serial number
[in] DateOfProduction = the Date of production
Definition at line 166 of file DlgModifySubModule.cpp.
void SystemTracking::CDlgModifySubModule::UpdateSubModule (ServiceDataManager::CSubModule & SubModule) [signal]
This signal is emitted when a program is updated.
Parameters:
[in] SubModule = Modified SubModule.
Referenced by OnSave().
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/DlgModifySubModule.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/DlgModifySubModule.cpp