Himalaya Service Master: SystemTracking::CLaSystem Class Reference
SystemTracking::CLaSystem Class Reference
This is the widget displaying to modify LA system config.
#include <LaSystem.h>
Public Slots
void UpdateSubModule (ServiceDataManager::CSubModule &SubModule)
slot for update sub module.
void ModifyPump (void)
slot for modify pump.
void ModifyValve1 (void)
slot for modify valve1.
void ModifyValve2 (void)
slot for modify valve2.
void ModifyHeatingBelt1 (void)
slot for modify heating belt1.
void ModifyHeatingBelt2 (void)
slot for modify heating belt2.
void ModifyPressureSensor (void)
slot for modify pressure sensor.
void ModifyCarbonFilter (void)
slot for modify carbon filter.
void ModifyFan (void)
slot for modify fan.
void OnFinalizeConfiguration (void)
slot for finalize configuration.
void CurrentTabChanged (int Index)
call slot when current tab changed.
void ConfirmModuleConfiguration ()
slot for confirm module configuration.
Signals
void ModuleListChanged (void)
signal for module list changed.
Public Member Functions
CLaSystem (Core::CServiceGUIConnector &DataConnector, QWidget *p_Parent=0)
Default constructor.
~CLaSystem (void)
Destructor.
Detailed Description
This is the widget displaying to modify LA system config.
Definition at line 39 of file LaSystem.h.
Constructor & Destructor Documentation
SystemTracking::CLaSystem::CLaSystem (Core::CServiceGUIConnector & DataConnector, QWidget * p_Parent = 0) [explicit]
Default constructor.
Parameters:
[in] DataConnector = service Gui connector
[in] p_Parent = parent of widget
Definition at line 42 of file LaSystem.cpp.
References ModifyCarbonFilter(), ModifyFan(), ModifyHeatingBelt1(), ModifyHeatingBelt2(), ModifyPressureSensor(), ModifyPump(), ModifyValve1(), ModifyValve2(), and OnFinalizeConfiguration().
SystemTracking::CLaSystem::~CLaSystem (void)
Destructor.
Definition at line 103 of file LaSystem.cpp.
Member Function Documentation
void SystemTracking::CLaSystem::ConfirmModuleConfiguration () [slot]
slot for confirm module configuration.
Definition at line 222 of file LaSystem.cpp.
Referenced by CurrentTabChanged(), and OnFinalizeConfiguration().
void SystemTracking::CLaSystem::CurrentTabChanged (int Index) [slot]
call slot when current tab changed.
Parameters:
Index = tab index
Definition at line 215 of file LaSystem.cpp.
References ConfirmModuleConfiguration().
void SystemTracking::CLaSystem::ModifyCarbonFilter (void) [slot]
slot for modify carbon filter.
Definition at line 191 of file LaSystem.cpp.
Referenced by CLaSystem().
void SystemTracking::CLaSystem::ModifyFan (void) [slot]
slot for modify fan.
Definition at line 199 of file LaSystem.cpp.
Referenced by CLaSystem().
void SystemTracking::CLaSystem::ModifyHeatingBelt1 (void) [slot]
slot for modify heating belt1.
Definition at line 167 of file LaSystem.cpp.
Referenced by CLaSystem().
void SystemTracking::CLaSystem::ModifyHeatingBelt2 (void) [slot]
slot for modify heating belt2.
Definition at line 175 of file LaSystem.cpp.
Referenced by CLaSystem().
void SystemTracking::CLaSystem::ModifyPressureSensor (void) [slot]
slot for modify pressure sensor.
Definition at line 183 of file LaSystem.cpp.
Referenced by CLaSystem().
void SystemTracking::CLaSystem::ModifyPump (void) [slot]
slot for modify pump.
Definition at line 143 of file LaSystem.cpp.
Referenced by CLaSystem().
void SystemTracking::CLaSystem::ModifyValve1 (void) [slot]
slot for modify valve1.
Definition at line 151 of file LaSystem.cpp.
Referenced by CLaSystem().
void SystemTracking::CLaSystem::ModifyValve2 (void) [slot]
slot for modify valve2.
Definition at line 159 of file LaSystem.cpp.
Referenced by CLaSystem().
void SystemTracking::CLaSystem::ModuleListChanged (void) [signal]
signal for module list changed.
void SystemTracking::CLaSystem::OnFinalizeConfiguration (void) [slot]
slot for finalize configuration.
Definition at line 207 of file LaSystem.cpp.
References ConfirmModuleConfiguration().
Referenced by CLaSystem().
void SystemTracking::CLaSystem::UpdateSubModule (ServiceDataManager::CSubModule & SubModule) [slot]
slot for update sub module.
Parameters:
SubModule = reference sub module object
Definition at line 114 of file LaSystem.cpp.
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/LaSystem.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/LaSystem.cpp