Himalaya Service Master: SystemTracking::CViewHistory Class Reference
SystemTracking::CViewHistory Class Reference
This widget displays history of ModuleList.
#include <ViewHistory.h>
Public Slots
void UpdateGUI (void)
Slot for updating the GUI.
void ExecDialog (void)
Pop's up a dialog for show detail.
void ExecDiffDialog (void)
Pop's up a dialog for show diff.
Public Member Functions
CViewHistory (Core::CServiceGUIConnector *p_DataConnector, QWidget *p_Parent=0)
Default constructor.
~CViewHistory (void)
Destructor.
void AddItem (QString TimeStamp)
To add data item to the table.
Detailed Description
This widget displays history of ModuleList.
Definition at line 45 of file ViewHistory.h.
Constructor & Destructor Documentation
SystemTracking::CViewHistory::CViewHistory (Core::CServiceGUIConnector * p_DataConnector, QWidget * p_Parent = 0) [explicit]
Default constructor.
Constructor.
Parameters:
[in] p_DataConnector = service Gui connector
[in] p_Parent = parent of widget
[in] p_Parent = Parent widget
Definition at line 41 of file ViewHistory.cpp.
References ExecDialog(), and ExecDiffDialog().
SystemTracking::CViewHistory::~CViewHistory (void)
Destructor.
Definition at line 78 of file ViewHistory.cpp.
Member Function Documentation
void SystemTracking::CViewHistory::AddItem (QString TimeStamp)
To add data item to the table.
Parameters:
[in] TimeStamp = time stamp
Definition at line 134 of file ViewHistory.cpp.
Referenced by UpdateGUI().
void SystemTracking::CViewHistory::ExecDialog (void) [slot]
Pop's up a dialog for show detail.
Pop's up a dialog to view Instrument History.
Definition at line 166 of file ViewHistory.cpp.
References SystemTracking::CViewHistoryDlg::SetModuleList(), and SystemTracking::CViewHistoryDlg::UpdateGUI().
Referenced by CViewHistory().
void SystemTracking::CViewHistory::ExecDiffDialog (void) [slot]
Pop's up a dialog for show diff.
Definition at line 198 of file ViewHistory.cpp.
References SystemTracking::CViewHistoryDiffDlg::Instance(), and SystemTracking::CViewHistoryDiffDlg::Show().
Referenced by CViewHistory().
void SystemTracking::CViewHistory::UpdateGUI (void) [slot]
Slot for updating the GUI.
Definition at line 142 of file ViewHistory.cpp.
References AddItem().
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/ViewHistory.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/ViewHistory.cpp