Himalaya Service Master: SystemTracking::CDlgModifyModule Class Reference
SystemTracking::CDlgModifyModule Class Reference
This class provides facility to add/modify module configuration.
#include <DlgModifyModule.h>
Public Slots
void UpdateGUI (void)
Slot for updating the GUI.
void UpdateGUI (const QString &SerialNumber, const QDate &DateOfProduction)
Slot for updating the GUI.
void OnEditSerialNumber (void)
Slot for Edit serial number.
void OnAutoDetect (void)
Slot for auto detect.
void OnSave (void)
Slot for save button.
Signals
void UpdateModule (ServiceDataManager::CModule &Module)
This signal is emitted when a Moudle is updated.
void AutoDetect (ServiceDataManager::CModule &Module)
This signal is emitted when clicked Auto detect button .
Public Member Functions
CDlgModifyModule (ServiceDataManager::CModule &Module, bool HasBoard=false, QWidget *p_Parent=0)
Default constructor.
~CDlgModifyModule ()
Destructor.
Detailed Description
This class provides facility to add/modify module configuration.
Definition at line 43 of file DlgModifyModule.h.
Constructor & Destructor Documentation
SystemTracking::CDlgModifyModule::CDlgModifyModule (ServiceDataManager::CModule & Module, bool HasBoard = false, QWidget * p_Parent = 0) [explicit]
Default constructor.
Parameters:
[in] Module = Reference of Module object
[in] HasBoard = flag of Board
[in] p_Parent = parent of widget
Definition at line 29 of file DlgModifyModule.cpp.
References OnAutoDetect(), OnEditSerialNumber(), OnSave(), and UpdateGUI().
SystemTracking::CDlgModifyModule::~CDlgModifyModule (void)
Destructor.
Definition at line 97 of file DlgModifyModule.cpp.
Member Function Documentation
void SystemTracking::CDlgModifyModule::AutoDetect (ServiceDataManager::CModule & Module) [signal]
This signal is emitted when clicked Auto detect button .
Parameters:
[in] Module = Modified Module.
Referenced by OnAutoDetect().
void SystemTracking::CDlgModifyModule::OnAutoDetect (void) [slot]
Slot for auto detect.
Slot for removing the module.
Definition at line 211 of file DlgModifyModule.cpp.
References AutoDetect().
Referenced by CDlgModifyModule().
void SystemTracking::CDlgModifyModule::OnEditSerialNumber (void) [slot]
Slot for Edit serial number.
Definition at line 112 of file DlgModifyModule.cpp.
Referenced by CDlgModifyModule().
void SystemTracking::CDlgModifyModule::OnSave (void) [slot]
Slot for save button.
This slot is called when Save button is clicked.
Returns:
Returns zero if module does not exists.
Definition at line 151 of file DlgModifyModule.cpp.
References UpdateModule().
Referenced by CDlgModifyModule().
void SystemTracking::CDlgModifyModule::UpdateGUI (void) [slot]
Slot for updating the GUI.
Definition at line 123 of file DlgModifyModule.cpp.
Referenced by CDlgModifyModule(), SystemTracking::COven::ModifyOven(), SystemTracking::CRetort::ModifyRetort(), and SystemTracking::CRotaryValve::ModifyRotaryValve().
void SystemTracking::CDlgModifyModule::UpdateGUI (const QString & SerialNumber, const QDate & DateOfProduction) [slot]
Slot for updating the GUI.
Parameters:
[in] SerialNumber = Module serial number
[in] DateOfProduction = the Date of production
Definition at line 132 of file DlgModifyModule.cpp.
void SystemTracking::CDlgModifyModule::UpdateModule (ServiceDataManager::CModule & Module) [signal]
This signal is emitted when a Moudle is updated.
Parameters:
[in] Module = Modified Module.
Referenced by OnSave().
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/DlgModifyModule.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/DlgModifyModule.cpp