Himalaya Service Master: SystemTracking::CRotaryValve Class Reference
SystemTracking::CRotaryValve Class Reference
This is the widget displaying to modify Rotary valve config.
#include <RotaryValve.h>
Public Slots
void UpdateModule (ServiceDataManager::CModule &Module)
slot for update module.
void UpdateSubModule (ServiceDataManager::CSubModule &SubModule)
slot for update sub module.
void ModifyRotaryValve (void)
slot for modify Rotary valve.
void ModifyHeater (void)
slot for modify Heater.
void ModifyMotor (void)
slot for modify Motor.
void OnFinalizeConfiguration (void)
slot for finalize configuration.
void CurrentTabChanged (int Index)
call slot when current tab changed.
void ConfirmModuleConfiguration ()
slot for confirm module configuration.
Signals
void ModuleListChanged (void)
signal for module list changed.
Public Member Functions
CRotaryValve (Core::CServiceGUIConnector &DataConnector, QWidget *p_Parent=0)
Default constructor.
~CRotaryValve (void)
Destructor.
Detailed Description
This is the widget displaying to modify Rotary valve config.
Definition at line 39 of file RotaryValve.h.
Constructor & Destructor Documentation
SystemTracking::CRotaryValve::CRotaryValve (Core::CServiceGUIConnector & DataConnector, QWidget * p_Parent = 0) [explicit]
Default constructor.
Parameters:
[in] DataConnector = service Gui connector
[in] p_Parent = parent of widget
Definition at line 37 of file RotaryValve.cpp.
References ModifyHeater(), ModifyMotor(), ModifyRotaryValve(), and OnFinalizeConfiguration().
SystemTracking::CRotaryValve::~CRotaryValve (void)
Destructor.
Definition at line 75 of file RotaryValve.cpp.
Member Function Documentation
void SystemTracking::CRotaryValve::ConfirmModuleConfiguration () [slot]
slot for confirm module configuration.
Definition at line 208 of file RotaryValve.cpp.
Referenced by CurrentTabChanged(), and OnFinalizeConfiguration().
void SystemTracking::CRotaryValve::CurrentTabChanged (int Index) [slot]
call slot when current tab changed.
Parameters:
Index = tab index
Definition at line 201 of file RotaryValve.cpp.
References ConfirmModuleConfiguration().
void SystemTracking::CRotaryValve::ModifyHeater (void) [slot]
slot for modify Heater.
Definition at line 177 of file RotaryValve.cpp.
Referenced by CRotaryValve().
void SystemTracking::CRotaryValve::ModifyMotor (void) [slot]
slot for modify Motor.
Definition at line 185 of file RotaryValve.cpp.
Referenced by CRotaryValve().
void SystemTracking::CRotaryValve::ModifyRotaryValve (void) [slot]
slot for modify Rotary valve.
Definition at line 137 of file RotaryValve.cpp.
References SystemTracking::CDlgModifyModule::UpdateGUI(), and UpdateModule().
Referenced by CRotaryValve().
void SystemTracking::CRotaryValve::ModuleListChanged (void) [signal]
signal for module list changed.
Referenced by UpdateModule().
void SystemTracking::CRotaryValve::OnFinalizeConfiguration (void) [slot]
slot for finalize configuration.
Definition at line 193 of file RotaryValve.cpp.
References ConfirmModuleConfiguration().
Referenced by CRotaryValve().
void SystemTracking::CRotaryValve::UpdateModule (ServiceDataManager::CModule & Module) [slot]
slot for update module.
Parameters:
Module = module object
Definition at line 85 of file RotaryValve.cpp.
References ModuleListChanged().
Referenced by ModifyRotaryValve().
void SystemTracking::CRotaryValve::UpdateSubModule (ServiceDataManager::CSubModule & SubModule) [slot]
slot for update sub module.
Parameters:
SubModule = sub module object
Definition at line 108 of file RotaryValve.cpp.
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/RotaryValve.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/RotaryValve.cpp