Himalaya Service Master: SystemTracking::COven Class Reference
SystemTracking::COven Class Reference
This is the widget displaying to modify Oven config.
#include <Oven.h>
Public Slots
void UpdateModule (ServiceDataManager::CModule &Module)
slot for update module.
void UpdateSubModule (ServiceDataManager::CSubModule &SubModule)
slot for update sub module.
void ModifyOven (void)
slot for modify Oven.
void ModifyHeater (void)
slot for modify Heater.
void ModifyCoverSensor (void)
slot for modify Cover Sensor.
void OnFinalizeConfiguration ()
slot for finalize configuration.
void CurrentTabChanged (int Index)
call slot when current tab changed.
void ConfirmModuleConfiguration ()
slot for confirm module configuration.
Signals
void ModuleListChanged (void)
signal for module list changed.
Public Member Functions
COven (Core::CServiceGUIConnector &DataConnector, QWidget *p_Parent=0)
Default constructor.
~COven (void)
Destructor.
Detailed Description
This is the widget displaying to modify Oven config.
Definition at line 39 of file Oven.h.
Constructor & Destructor Documentation
SystemTracking::COven::COven (Core::CServiceGUIConnector & DataConnector, QWidget * p_Parent = 0) [explicit]
Default constructor.
Parameters:
[in] DataConnector = service Gui connector
[in] p_Parent = parent of widget
Definition at line 37 of file Oven.cpp.
References ModifyCoverSensor(), ModifyHeater(), ModifyOven(), and OnFinalizeConfiguration().
SystemTracking::COven::~COven (void)
Destructor.
Definition at line 74 of file Oven.cpp.
Member Function Documentation
void SystemTracking::COven::ConfirmModuleConfiguration () [slot]
slot for confirm module configuration.
Definition at line 196 of file Oven.cpp.
Referenced by CurrentTabChanged(), and OnFinalizeConfiguration().
void SystemTracking::COven::CurrentTabChanged (int Index) [slot]
call slot when current tab changed.
Parameters:
Index = tab index
Definition at line 189 of file Oven.cpp.
References ConfirmModuleConfiguration().
void SystemTracking::COven::ModifyCoverSensor (void) [slot]
slot for modify Cover Sensor.
Definition at line 173 of file Oven.cpp.
Referenced by COven().
void SystemTracking::COven::ModifyHeater (void) [slot]
slot for modify Heater.
Definition at line 165 of file Oven.cpp.
Referenced by COven().
void SystemTracking::COven::ModifyOven (void) [slot]
slot for modify Oven.
Definition at line 129 of file Oven.cpp.
References SystemTracking::CDlgModifyModule::UpdateGUI(), and UpdateModule().
Referenced by COven().
void SystemTracking::COven::ModuleListChanged (void) [signal]
signal for module list changed.
void SystemTracking::COven::OnFinalizeConfiguration (void) [slot]
slot for finalize configuration.
Definition at line 181 of file Oven.cpp.
References ConfirmModuleConfiguration().
Referenced by COven().
void SystemTracking::COven::UpdateModule (ServiceDataManager::CModule & Module) [slot]
slot for update module.
Parameters:
Module = module object
Definition at line 84 of file Oven.cpp.
Referenced by ModifyOven().
void SystemTracking::COven::UpdateSubModule (ServiceDataManager::CSubModule & SubModule) [slot]
slot for update sub module.
Parameters:
SubModule = sub module object
Definition at line 100 of file Oven.cpp.
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/Oven.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/Oven.cpp