Himalaya Service Master: SystemTracking::CCurrentConfigurationDlg Class Reference
SystemTracking::CCurrentConfigurationDlg Class Reference
This is the dialog for displaying module information.
#include <CurrentConfigurationDlg.h>
Public Slots
void ExecDialog ()
Pop's up a dialog for SubModule parameters.
void OnCancel ()
Definition/Declaration of OnCancel.
Public Member Functions
CCurrentConfigurationDlg (QWidget *p_Parent=NULL)
Default constructor.
~CCurrentConfigurationDlg ()
Destructor.
void AddItem (const QString &SubModuleName)
To add data item to the table.
void InitDialog (ServiceDataManager::CModule *p_Module)
To initialize the pop up dialog.
Protected Member Functions
void changeEvent (QEvent *p_Event)
Definition/Declaration of function changeEvent.
Detailed Description
This is the dialog for displaying module information.
Definition at line 43 of file CurrentConfigurationDlg.h.
Constructor & Destructor Documentation
SystemTracking::CCurrentConfigurationDlg::CCurrentConfigurationDlg (QWidget * p_Parent = NULL) [explicit]
Default constructor.
Constructor.
Parameters:
[in] p_Parent = parent of widget
[in] p_Parent = Parent widget
Definition at line 35 of file CurrentConfigurationDlg.cpp.
References ExecDialog(), and OnCancel().
SystemTracking::CCurrentConfigurationDlg::~CCurrentConfigurationDlg ()
Destructor.
Definition at line 77 of file CurrentConfigurationDlg.cpp.
Member Function Documentation
void SystemTracking::CCurrentConfigurationDlg::AddItem (const QString & SubModuleName)
To add data item to the table.
Parameters:
[in] SubModuleName = Name of the module
Definition at line 96 of file CurrentConfigurationDlg.cpp.
Referenced by InitDialog().
void SystemTracking::CCurrentConfigurationDlg::changeEvent (QEvent * p_Event) [protected]
Definition/Declaration of function changeEvent.
Parameters:
p_Event = QEvent type parameter
Returns:
from changeEvent
Definition at line 120 of file CurrentConfigurationDlg.cpp.
void SystemTracking::CCurrentConfigurationDlg::ExecDialog (void) [slot]
Pop's up a dialog for SubModule parameters.
Pop's up a dialog to display submodule information.
Definition at line 138 of file CurrentConfigurationDlg.cpp.
References SystemTracking::CCurrentConfigParameterDlg::ClearModel(), and SystemTracking::CCurrentConfigParameterDlg::InitDialog().
Referenced by CCurrentConfigurationDlg().
void SystemTracking::CCurrentConfigurationDlg::InitDialog (ServiceDataManager::CModule * p_Module)
To initialize the pop up dialog.
Parameters:
[in] p_Module = Module object
Definition at line 182 of file CurrentConfigurationDlg.cpp.
References AddItem().
Referenced by SystemTracking::CCurrentConfiguration::ExecDialog().
void SystemTracking::CCurrentConfigurationDlg::OnCancel () [slot]
Definition/Declaration of OnCancel.
Definition at line 170 of file CurrentConfigurationDlg.cpp.
Referenced by CCurrentConfigurationDlg().
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/CurrentConfigurationDlg.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/CurrentConfigurationDlg.cpp