Himalaya Service Master: SystemTracking::CMainControl Class Reference
SystemTracking::CMainControl Class Reference
This is the widget displaying to modify main control config.
#include <MainControl.h>
Public Slots
void UpdateSubModule (ServiceDataManager::CSubModule &SubModule)
slot for update sub module.
void ModifyEBox (void)
slot for modify E box.
void ModifyASB3 (void)
slot for modify ASB3.
void ModifyASB5 (void)
slot for modify ASB5.
void ModifyASB15 (void)
slot for modify ASB15.
void ModifyTouchScreen (void)
slot for modify Touch screen.
void ModifyVentFan (void)
slot for modify Vent fan.
void OnFinalizeConfiguration (void)
slot for finalize configuration.
void CurrentTabChanged (int Index)
call slot when current tab changed.
void ConfirmModuleConfiguration ()
slot for confirm module configuration.
Signals
void ModuleListChanged (void)
signal for module list changed.
void PerformManufacturingTest (Service::ModuleTestCaseID Test, Service::ModuleTestCaseID AbortId=Service::TEST_CASE_ID_UNUSED)
Signal emitted to perform manufacturing tests.
Public Member Functions
CMainControl (Core::CServiceGUIConnector &DataConnector, QWidget *p_Parent=0)
Default constructor.
~CMainControl (void)
Destructor.
Detailed Description
This is the widget displaying to modify main control config.
Definition at line 40 of file MainControl.h.
Constructor & Destructor Documentation
SystemTracking::CMainControl::CMainControl (Core::CServiceGUIConnector & DataConnector, QWidget * p_Parent = 0) [explicit]
Default constructor.
Parameters:
[in] DataConnector = service Gui connector
[in] p_Parent = parent of widget
Definition at line 45 of file MainControl.cpp.
References ModifyASB15(), ModifyASB3(), ModifyASB5(), ModifyEBox(), ModifyTouchScreen(), ModifyVentFan(), and OnFinalizeConfiguration().
SystemTracking::CMainControl::~CMainControl (void)
Destructor.
Definition at line 97 of file MainControl.cpp.
Member Function Documentation
void SystemTracking::CMainControl::ConfirmModuleConfiguration () [slot]
slot for confirm module configuration.
Definition at line 203 of file MainControl.cpp.
Referenced by CurrentTabChanged(), and OnFinalizeConfiguration().
void SystemTracking::CMainControl::CurrentTabChanged (int Index) [slot]
call slot when current tab changed.
Parameters:
Index = tab index
Definition at line 196 of file MainControl.cpp.
References ConfirmModuleConfiguration().
void SystemTracking::CMainControl::ModifyASB15 (void) [slot]
slot for modify ASB15.
Definition at line 160 of file MainControl.cpp.
Referenced by CMainControl().
void SystemTracking::CMainControl::ModifyASB3 (void) [slot]
slot for modify ASB3.
Definition at line 142 of file MainControl.cpp.
Referenced by CMainControl().
void SystemTracking::CMainControl::ModifyASB5 (void) [slot]
slot for modify ASB5.
Definition at line 151 of file MainControl.cpp.
Referenced by CMainControl().
void SystemTracking::CMainControl::ModifyEBox (void) [slot]
slot for modify E box.
Definition at line 133 of file MainControl.cpp.
Referenced by CMainControl().
void SystemTracking::CMainControl::ModifyTouchScreen (void) [slot]
slot for modify Touch screen.
Definition at line 169 of file MainControl.cpp.
Referenced by CMainControl().
void SystemTracking::CMainControl::ModifyVentFan (void) [slot]
slot for modify Vent fan.
Definition at line 178 of file MainControl.cpp.
Referenced by CMainControl().
void SystemTracking::CMainControl::ModuleListChanged (void) [signal]
signal for module list changed.
void SystemTracking::CMainControl::OnFinalizeConfiguration (void) [slot]
slot for finalize configuration.
Definition at line 187 of file MainControl.cpp.
References ConfirmModuleConfiguration().
Referenced by CMainControl().
void SystemTracking::CMainControl::PerformManufacturingTest (Service::ModuleTestCaseID Test, Service::ModuleTestCaseID AbortId = Service::TEST_CASE_ID_UNUSED) [signal]
Signal emitted to perform manufacturing tests.
Parameters:
[in] Test = Test name
[in] AbortId = Test abort id
void SystemTracking::CMainControl::UpdateSubModule (ServiceDataManager::CSubModule & SubModule) [slot]
slot for update sub module.
Parameters:
SubModule = sub module object
Definition at line 107 of file MainControl.cpp.
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/MainControl.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/MainControl.cpp