Himalaya Service Master: SystemTracking::CRetort Class Reference
SystemTracking::CRetort Class Reference
This is the widget displaying to modify Retort config.
#include <Retort.h>
Public Slots
void UpdateModule (ServiceDataManager::CModule &Module)
slot for update module.
void UpdateSubModule (ServiceDataManager::CSubModule &SubModule)
slot for update sub module.
void ModifyRetort (void)
slot for modify Retort.
void ModifyHeater (void)
slot for modify Heater.
void ModifyLidLock (void)
slot for modify Lid lock.
void ModifyLevelSensor (void)
slot for modify Level sensor.
void OnFinalizeConfiguration (void)
slot for finalize configuration.
void CurrentTabChanged (int Index)
call slot when current tab changed.
void ConfirmModuleConfiguration ()
slot for confirm module configuration.
Signals
void ModuleListChanged (void)
signal for module list changed.
Public Member Functions
CRetort (Core::CServiceGUIConnector &DataConnector, QWidget *p_Parent=0)
Default constructor.
~CRetort (void)
Destructor.
Detailed Description
This is the widget displaying to modify Retort config.
Definition at line 39 of file Retort.h.
Constructor & Destructor Documentation
SystemTracking::CRetort::CRetort (Core::CServiceGUIConnector & DataConnector, QWidget * p_Parent = 0) [explicit]
Default constructor.
Parameters:
[in] DataConnector = service Gui connector
[in] p_Parent = parent of widget
Definition at line 38 of file Retort.cpp.
References ModifyHeater(), ModifyLevelSensor(), ModifyLidLock(), ModifyRetort(), and OnFinalizeConfiguration().
SystemTracking::CRetort::~CRetort (void)
Destructor.
Definition at line 80 of file Retort.cpp.
Member Function Documentation
void SystemTracking::CRetort::ConfirmModuleConfiguration () [slot]
slot for confirm module configuration.
Definition at line 220 of file Retort.cpp.
Referenced by CurrentTabChanged(), and OnFinalizeConfiguration().
void SystemTracking::CRetort::CurrentTabChanged (int Index) [slot]
call slot when current tab changed.
Parameters:
Index = tab index
Definition at line 213 of file Retort.cpp.
References ConfirmModuleConfiguration().
void SystemTracking::CRetort::ModifyHeater (void) [slot]
slot for modify Heater.
Definition at line 181 of file Retort.cpp.
Referenced by CRetort().
void SystemTracking::CRetort::ModifyLevelSensor (void) [slot]
slot for modify Level sensor.
Definition at line 197 of file Retort.cpp.
Referenced by CRetort().
void SystemTracking::CRetort::ModifyLidLock (void) [slot]
slot for modify Lid lock.
Definition at line 189 of file Retort.cpp.
Referenced by CRetort().
void SystemTracking::CRetort::ModifyRetort (void) [slot]
slot for modify Retort.
Definition at line 141 of file Retort.cpp.
References SystemTracking::CDlgModifyModule::UpdateGUI(), and UpdateModule().
Referenced by CRetort().
void SystemTracking::CRetort::ModuleListChanged (void) [signal]
signal for module list changed.
Referenced by UpdateModule().
void SystemTracking::CRetort::OnFinalizeConfiguration (void) [slot]
slot for finalize configuration.
Definition at line 205 of file Retort.cpp.
References ConfirmModuleConfiguration().
Referenced by CRetort().
void SystemTracking::CRetort::UpdateModule (ServiceDataManager::CModule & Module) [slot]
slot for update module.
Parameters:
Module = module object
Definition at line 90 of file Retort.cpp.
References ModuleListChanged().
Referenced by ModifyRetort().
void SystemTracking::CRetort::UpdateSubModule (ServiceDataManager::CSubModule & SubModule) [slot]
slot for update sub module.
Parameters:
SubModule = sub module object
Definition at line 112 of file Retort.cpp.
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/Retort.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/Retort.cpp