Himalaya Service Master: SystemTracking::CCurrentConfiguration Class Reference
SystemTracking::CCurrentConfiguration Class Reference
This is the widget displaying Modules.
#include <CurrentConfiguration.h>
Public Slots
void ExecDialog (void)
Pop's up a dialog for SubModuleList.
void UpdateGUI (void)
Slot for updating the GUI.
Public Member Functions
CCurrentConfiguration (Core::CServiceGUIConnector *p_DataConnector, QWidget *p_Parent=0)
Default constructor.
~CCurrentConfiguration ()
Destructor.
void AddItem (const QString &ModuleName)
To add data item to the table.
Protected Member Functions
void changeEvent (QEvent *p_Event)
Definition/Declaration of function changeEvent.
Detailed Description
This is the widget displaying Modules.
Definition at line 45 of file CurrentConfiguration.h.
Constructor & Destructor Documentation
SystemTracking::CCurrentConfiguration::CCurrentConfiguration (Core::CServiceGUIConnector * p_DataConnector, QWidget * p_Parent = 0) [explicit]
Default constructor.
Constructor.
Parameters:
[in] p_DataConnector = service Gui connector, p_Parent = parent of widget
[in] p_Parent = Parent widget
Definition at line 34 of file CurrentConfiguration.cpp.
References ExecDialog().
SystemTracking::CCurrentConfiguration::~CCurrentConfiguration ()
Destructor.
Definition at line 65 of file CurrentConfiguration.cpp.
Member Function Documentation
void SystemTracking::CCurrentConfiguration::AddItem (const QString & ModuleName)
To add data item to the table.
Parameters:
[in] ModuleName = Name of the module
Definition at line 119 of file CurrentConfiguration.cpp.
Referenced by UpdateGUI().
void SystemTracking::CCurrentConfiguration::changeEvent (QEvent * p_Event) [protected]
Definition/Declaration of function changeEvent.
Event handler for change events.
Parameters:
p_Event = QEvent type parameter
Returns:
from changeEvent
Parameters:
[in] p_Event = Change event
Definition at line 133 of file CurrentConfiguration.cpp.
void SystemTracking::CCurrentConfiguration::ExecDialog (void) [slot]
Pop's up a dialog for SubModuleList.
Definition at line 150 of file CurrentConfiguration.cpp.
References SystemTracking::CCurrentConfigurationDlg::InitDialog().
Referenced by CCurrentConfiguration().
void SystemTracking::CCurrentConfiguration::UpdateGUI (void) [slot]
Slot for updating the GUI.
Definition at line 83 of file CurrentConfiguration.cpp.
References AddItem().
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/CurrentConfiguration.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/CurrentConfiguration.cpp