Himalaya Service Master: SystemTracking::CCurrentConfigParameterDlg Class Reference
SystemTracking::CCurrentConfigParameterDlg Class Reference
This is the dialog for displaying sub module information.
#include <CurrentConfigParameterDlg.h>
Public Member Functions
CCurrentConfigParameterDlg (QWidget *p_Parent=NULL)
Default constructor.
~CCurrentConfigParameterDlg ()
Destructor.
void AddItem (const QString &ParamName, const QString &ParamValue)
To add data item to the table.
void InitDialog (ServiceDataManager::Parameter_t *p_Parameter)
To initialize the pop up dialog.
void ClearModel ()
To clear the table model.
Protected Member Functions
void changeEvent (QEvent *p_Event)
Definition/Declaration of function changeEvent.
Detailed Description
This is the dialog for displaying sub module information.
Definition at line 42 of file CurrentConfigParameterDlg.h.
Constructor & Destructor Documentation
SystemTracking::CCurrentConfigParameterDlg::CCurrentConfigParameterDlg (QWidget * p_Parent = NULL)
Default constructor.
Constructor.
Parameters:
[in] p_Parent = parent of widget
[in] p_Parent = Parent widget
Definition at line 39 of file CurrentConfigParameterDlg.cpp.
SystemTracking::CCurrentConfigParameterDlg::~CCurrentConfigParameterDlg ()
Destructor.
Definition at line 63 of file CurrentConfigParameterDlg.cpp.
Member Function Documentation
void SystemTracking::CCurrentConfigParameterDlg::AddItem (const QString & ParamName, const QString & ParamValue)
To add data item to the table.
Parameters:
[in] ParamName = Name of the Parameter
[in] ParamValue = Value of the Parameter
Definition at line 117 of file CurrentConfigParameterDlg.cpp.
Referenced by InitDialog().
void SystemTracking::CCurrentConfigParameterDlg::changeEvent (QEvent * p_Event) [protected]
Definition/Declaration of function changeEvent.
Event handler for change events.
Parameters:
p_Event = QEvent type parameter
Returns:
from changeEvent
Parameters:
[in] p_Event = Change event
Definition at line 81 of file CurrentConfigParameterDlg.cpp.
void SystemTracking::CCurrentConfigParameterDlg::ClearModel ()
To clear the table model.
Definition at line 136 of file CurrentConfigParameterDlg.cpp.
Referenced by SystemTracking::CCurrentConfigurationDlg::ExecDialog().
void SystemTracking::CCurrentConfigParameterDlg::InitDialog (ServiceDataManager::Parameter_t * p_Parameter)
To initialize the pop up dialog.
Parameters:
[in] p_Parameter = Pointer to Parameter Struct
Definition at line 100 of file CurrentConfigParameterDlg.cpp.
References AddItem().
Referenced by SystemTracking::CCurrentConfigurationDlg::ExecDialog().
The documentation for this class was generated from the following files:
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Include/CurrentConfigParameterDlg.h
/home/ldx/workspaces/Himalaya/ServiceSW/Master/Components/SystemTracking/Source/CurrentConfigParameterDlg.cpp